# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: folder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'folder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66older.proto\"\x1d\n\rFolderRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"#\n\x0e\x46olderResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t2=\n\rFolderService\x12,\n\tListFiles\x12\x0e.FolderRequest\x1a\x0f.FolderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'folder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOLDERREQUEST']._serialized_start=16
  _globals['_FOLDERREQUEST']._serialized_end=45
  _globals['_FOLDERRESPONSE']._serialized_start=47
  _globals['_FOLDERRESPONSE']._serialized_end=82
  _globals['_FOLDERSERVICE']._serialized_start=84
  _globals['_FOLDERSERVICE']._serialized_end=145
# @@protoc_insertion_point(module_scope)
